version: "3"

services:
#PHP Service
  project-php:
    container_name: project-php
    hostname: project-php
    build: .
    volumes:
      - ./files/project_files:/var/www/project
    restart: unless-stopped
    networks:
      - main

#Network configuration
networks:
  main:
     external: true
